### ISSUE TITLE
How to configure static ip?

### ISSUE THREAD

**Issue by A-Saav** [Jpe230/SonicPad-Debian#14]
Is there a way to set a static ip or a url like in CSP Stock (http://spad-5123.local)

**Comment by beroliv** [comment]
i told my dhcp server to give him a specific adress. you could edit your interfaces file. but if someting goes wrong you have no access to you pad anymore

https://www.cyberciti.biz/faq/add-configure-set-up-static-ip-address-on-debianlinux

**Comment by A-Saav** [comment]
I had to do it from dhcp because yesterday I tried it directly from ssh but I did a wrong step and I lost access and I don't want to lose it again
