### ISSUE TITLE
unable to open a gcode file

### ISSUE THREAD

**Issue by Tance85** [Jpe230/SonicPad-Debian#17]
I've managed to get everything up and running but when i send a file to the pad it tells me that it's unable to load the file

**Comment by beroliv** [comment]
check your Path

`[virtual_sdcard]
path: /home/sonic/printer_data/gcodes`

**Comment by Tance85** [comment]
Thanks don't know how I missed that. I was pretty sure I copied and pasted everything over from the original config. problem solved. As i suspected all my fault lol.
