### ISSUE TITLE
How do I rotate the display?

### ISSUE THREAD

**Issue by BakeJake** [Jpe230/SonicPad-Debian#18]
I'd love to use this but with my current configuration I cant have the screen in its original orientation, needing to flip it but couldn't figure out how to do it.

**Comment by Jpe230** [comment]
https://github.com/Jpe230/SonicPad-Debian/issues/7#issuecomment-1620587643

**Comment by Jpe230** [comment]
> > [#7 (comment)](https://github.com/Jpe230/SonicPad-Debian/issues/7#issuecomment-1620587643)
> 
> @Jpe230 
> 
> Where do I put this?
> 
> `DISPLAY=:0 xinput set-prop 7 'Coordinate Transformation Matrix' -1 0 1 0 -1 1 0 0 1`
> 
> Nvm, it says to run in terminal on klipperscreen docs, thanks!

That's a command, you can enter it manually in the terminal or a script at boot-time (rc.local or systemd)

**Comment by BakeJake** [comment]
> > > [#7 (comment)](https://github.com/Jpe230/SonicPad-Debian/issues/7#issuecomment-1620587643)
> > 
> > 
> > @Jpe230
> > Where do I put this?
> > `DISPLAY=:0 xinput set-prop 7 'Coordinate Transformation Matrix' -1 0 1 0 -1 1 0 0 1`
> > Nvm, it says to run in terminal on klipperscreen docs, thanks!
> 
> That's a command, you can enter it manually in the terminal or a script at boot-time (rc.local or systemd)

@Jpe230 How would I make that boot script?

**Comment by BakeJake** [comment]
> > > [#7 (comment)](https://github.com/Jpe230/SonicPad-Debian/issues/7#issuecomment-1620587643)
> > 
> > 
> > @Jpe230
> > Where do I put this?
> > `DISPLAY=:0 xinput set-prop 7 'Coordinate Transformation Matrix' -1 0 1 0 -1 1 0 0 1`
> > Nvm, it says to run in terminal on klipperscreen docs, thanks!
> 
> That's a command, you can enter it manually in the terminal or a script at boot-time (rc.local or systemd)

@Jpe230, 
What fixed it for me was the bottom part of this with the values for flipping instead of those "-1 0 1 0 -1 1 0 0 1" and the device id of 7:
![image](https://github.com/Jpe230/SonicPad-Debian/assets/52101762/be8787e6-74de-4309-82ae-fdf0d6e79874)
