### ISSUE TITLE
need the password for "ssh sonic@ip_address"

### ISSUE THREAD

**Issue by NoodleSploder** [Jpe230/SonicPad-Debian#2]
When trying to SSH for the first time it is asking me for a password.  I didn't see any notes about a password.

![image](https://github.com/Jpe230/SonicPad-Debian/assets/2625732/332631c1-7685-406d-b2e7-9e412b41a2cc)

I appreciate your effort on this!

NS

**Comment by nofuturekid** [comment]
You haven't read the text before downloading...

sonic:pad
root:toor

**Comment by NoodleSploder** [comment]
Sorry, yes, on the releases page I see it.  I need more sleep.  Thanks
