### ISSUE TITLE
time setting

### ISSUE THREAD

**Issue by m4sis** [Jpe230/SonicPad-Debian#20]
Good morning,
how to set your time I can't find how to do it.
kliperscreen shows wrong time

**Comment by mdewyer** [comment]
I was able to fix mine by running this command in ssh:
`sudo timedatectl set-timezone America/Chicago`

It had orginally been set to "America/Mexico_City"

Here's a good article that covers timezones in Debian: https://linuxize.com/post/how-to-set-or-change-timezone-on-debian-10/

**Comment by m4sis** [comment]
Thanks it works

**Comment by m4sis** [comment]
Thanks it works
