### ISSUE TITLE
None make the Klipper 'make' tools work...

### ISSUE THREAD

**Issue by imacmill** [Jpe230/SonicPad-Debian#24]
I'm not at my printer ATM, but wanted to know if anyone has successfully run the 'make' tools for Klipper provided on this image.

I want to create firmware for my SOVOL SV06-PLUS printer, so I tried this:
 
Run 'make menuconfig'. I get a 'locale' error of some kind, which I ended up 'fixing' by entering some command I found on Google (can't recall command, but suffice to say it does survive a reboot...I need to enter the command every time 'make menuconfig' is run).

After successful 'menuconfig', I run 'make' alone and I get GCC errors. Again, not at my Sonicpad/printer, so can't say what they were -- something about missing OBJs --  but ultimately it shouldn't matter, as the Debian image should not be having 'make' problems (unless .

Is anyone maintaining this image that can confirm the 'make' issues and provide a remedy?

**Comment by nofuturekid** [comment]
Your first problem seems related to you using a Mac, right?
Other than that, "make" works as expected.

**Comment by nofuturekid** [comment]
Your error message is a little unspecific but are you sure you made the filesystem resize, because I have the feeling you forget about that and now are running out of space.

**Comment by imacmill** [comment]
> Your first problem seems related to you using a Mac, right? Other than that, "make" works as expected.

These issues are from using the Klipper 'make' tools installed on the Debian image installed on Debian Sonicpad image provided in this GIT. I installed the image on the the Sonicpad, SSH into it, and run Klipper's 'make' tools (which fail).

This is not related in any way to my PC (which is a Linux Mint box, FWIW).

**Comment by nofuturekid** [comment]
Not sure what you installed then on your SonicPad, but from what I and a couple of others can tell, is that it is working. As said some Mac users had smaller issues, related to "locale" due to their terminal program.

So you might try a different terminal program or settings.

**Comment by nofuturekid** [comment]
Maybe it makes more sense and is easier to diagnose when you paste the exact error messages you got when you are back on your Pad again. Otherwise it will just guesswork and waste of your and others time.

**Comment by imacmill** [comment]
> Not sure what you installed then on your SonicPad, but from what I and a couple of others can tell, is that it is working. As said some Mac users had smaller issues, related to "locale" due to their terminal program.
> 
> So you might try a different terminal program or settings.
> 
> I also understood that you are running it on the SonicPad... but you haven't answered my question about the filesystem resize...

I haven't answered your question about the file system resize because that request came in after I answered your first question, then walked away. A tad agressive. 

I did not see anything in the docs about a file system resize... I'll re-read them.

**Comment by nofuturekid** [comment]
Sorry, I'm not the one who came bare handed complaining. I can either shut up or you help me in the try to help you. Your decision.

**Comment by imacmill** [comment]
You're utterly irrational.

I'll move along.

**Comment by sfeole** [comment]
> I'm not at my printer ATM, but wanted to know if anyone has successfully run the 'make' tools for Klipper provided on this image.
> 
> I want to create firmware for my SOVOL SV06-PLUS printer, so I tried this:
> 
> Run 'make menuconfig'. I get a 'locale' error of some kind, which I ended up 'fixing' by entering some command I found on Google (can't recall command, but suffice to say it does survive a reboot...I need to enter the command every time 'make menuconfig' is run).
> 
> After successful 'menuconfig', I run 'make' alone and I get GCC errors. Again, not at my Sonicpad/printer, so can't say what they were -- something about missing OBJs -- but ultimately it shouldn't matter, as the Debian image should not be having 'make' problems (unless .
> 
> Is anyone maintaining this image that can confirm the 'make' issues and provide a remedy?

@imacmill Generally when filing bugs it's helpful to add the output of the error, if you had some time to paste that. I could take a shot at helping you.
