### ISSUE TITLE
Idle Timeout

### ISSUE THREAD

**Issue by erwann17** [Jpe230/SonicPad-Debian#29]
Hello

thanks a lot for tis project

Have you successfully corrected the Idle Timeout? If so, will there be an update?

**Comment by calculous** [comment]
Try method explained here: https://github.com/calculous/SonicPad-Debian#-future-updates

**Comment by erwann17** [comment]
Thanks 
that work great

**Comment by Jpe230** [comment]
Closing this issue since it now included in the latest release
