### ISSUE TITLE
sudo brightness not permanent

### ISSUE THREAD

**Issue by JurajMik** [Jpe230/SonicPad-Debian#30]
I want to set brightnes for my Sonic Pad. Running sudo brightness -v0 works, but is valid until restart, or new switch off/on.
Maybe I'm missing some other command - I'm newbie in Linux, even if very experienced in C++/C#

**Comment by sfeole** [comment]
@JurajMik In Debian you can do this with systemd or rc scripts.  

Here is a [helpful link](https://www.fosslinux.com/50812/run-script-boot-up-debian.htm) to get you started :)
