### ISSUE TITLE
Input Shaping with Creality Accelerometer 

### ISSUE THREAD

**Issue by tghelmbrecht** [Jpe230/SonicPad-Debian#35]
Hello,

How do I access the AXDL345 accelerometer that Creality provides, when using Debian? It doesn't show up as a USB device (because it's not), so I'm unsure how to configure it. I tried using the official guide with SPI, but it didn't work. Please let me know how you got this to work.

**Comment by nofuturekid** [comment]
It works exactly like if you have the Creality OS installed.
Look into the already closed topics, you are not the first one.

**Comment by Jpe230** [comment]
Please see the following issue :) https://github.com/Jpe230/SonicPad-Debian/issues/4
