### ISSUE TITLE
Resonance Calibration

### ISSUE THREAD

**Issue by Neckr0ik** [Jpe230/SonicPad-Debian#37]
After a large fine tuning to make it work again with my Ender 3 v2 Neo, I finally have the Sonic Pad with native Klipper, but i don't have any clues to get the accelerometer sensor to do a resonance calibration.
Any one has the printer.cfg file for this?

**Comment by Jpe230** [comment]
https://github.com/Jpe230/SonicPad-Debian/issues/4
