### ISSUE TITLE
factory reset

### ISSUE THREAD

**Issue by m4sis** [Jpe230/SonicPad-Debian#41]
Good morning, Is it possible to format everything and return to the initial configuration of creality?

**Comment by nofuturekid** [comment]
Exact the same way you flashed the Debian image, except of course using the Creality image.

**Comment by sfeole** [comment]
> Good morning, Is it possible to format everything and return to the initial configuration of creality?

https://github.com/CrealityOfficial/Creality_Sonic_Pad_Firmware
