### ISSUE TITLE
MCU protocol error

### ISSUE THREAD

**Issue by Scipolah** [Jpe230/SonicPad-Debian#44]
after updating klipper today i got this error, I compiled new firmwares various times, nothing worked. I temporarily went back to marlin and it was working so it's not an hardware issue. Tell me if there is any log or more information needed.
![Screenshot 2024-01-29 203707](https://github.com/Jpe230/SonicPad-Debian/assets/147976073/dfc92860-eb00-4c7f-aa3d-ac652a981fcc)

**Comment by nolan1958** [comment]
https://www.youtube.com/watch?v=cnthbR3tS9M This willl fix it.
