### ISSUE TITLE
Host shutdown and reboot from the fluidd menu

### ISSUE THREAD

**Issue by sahuddy** [Jpe230/SonicPad-Debian#45]
Is there a way to enable the host shutdown and reboot buttons in the fluidd ellipsis menu?  
When I click them after a fresh installation, nothing happens.  Thanks in advance!

**Comment by sahuddy** [comment]
Please disregard.  The solution is here: https://docs.fluidd.xyz/faq#the-host-reboot--shutdown-commands-dont-work

**Comment by Brakisshuro** [comment]
> Please disregard. The solution is here: https://docs.fluidd.xyz/faq#the-host-reboot--shutdown-commands-dont-work

i tried that command and no luck, says command not found.

**Comment by sahuddy** [comment]
Hmmm....maybe moonraker needs to be updated?  It worked for me,

**Comment by Brakisshuro** [comment]
> Hmmm....maybe moonraker needs to be updated? I'm at v0.8.0-317 and it worked for me,

You copied and pasted That exact command and hit enter? Everything I have is 100% updated

**Comment by sahuddy** [comment]
I sure did.

**Comment by Brakisshuro** [comment]
> I sure did.

Interesting, okay thank you

**Comment by Brakisshuro** [comment]
> I sure did. If it is there though, after changing into the directory, try ./sudo_fix.sh

Are you cd /klipper/ or are you doing it from the root prompt

**Comment by sahuddy** [comment]
When connecting, I land in /home/sonic.  From there the provided path works: ./moonraker/scripts/sudo-fix.sh, because I can also cd to ./moonraker/scripts/ run ls (list) and see the sudo-fix.sh script.

**Comment by Brakisshuro** [comment]
> When connecting, I land in /home/sonic. From there the provided path works: ./moonraker/scripts/sudo-fix.sh, because I can also cd to ./moonraker/scripts/ run ls (list) and see the sudo-fix.sh script.

I found the script I try to run it and it says command not found. Very weird. I'm in the Moonraker directory right now

**Comment by sahuddy** [comment]
From that directory, try: sudo ./sudo-fix.sh

**Comment by Brakisshuro** [comment]
> From that directory, try: sudo ./sudo-fix.sh

sonic@tony:~/moonraker/scripts$ sudo ./sudo_fix.sh
This script must not run as root

**Comment by sahuddy** [comment]
Ug.  So just: ./sudo_fix.sh then

**Comment by sahuddy** [comment]
Cool...sounds like you're good to go.  Have a great night!
