### ISSUE TITLE
Switch between 2 printers

### ISSUE THREAD

**Issue by Matze9876** [Jpe230/SonicPad-Debian#46]
Hello everyone, 
according to your instructions I successfully installed debian and klipper. 
Thank you very much for this. 
But how can I switch between my two printers on the SonicPad (Klipper Screen). 
Only one is shown at a time.
Where do I have to enter or change something?
I would like to thank you in advance for your support.

Best regards

**Comment by sahuddy** [comment]
Maybe this will help: https://www.youtube.com/watch?v=Dxjh4iVUL-4
