### ISSUE TITLE
new R818 Repository issue

### ISSUE THREAD

**Issue by HoudiniCerini** [Jpe230/SonicPad-Debian#56]
I'm stuck! 
i flashed everything klipper screen is open and i set up wifi
when i try to sudo apt-get update && sudo apt-get upgrade this is the issue i get
Hit:1 http://deb.debian.org/debian bullseye InRelease
Reading package lists... Done
E: Release file for http://deb.debian.org/debian/dists/bullseye/InRelease is not valid yet (invalid for another 236d 21h 13min 51s). Updates for this repository will not be applied.
Is there a discord for this by chance?

**Comment by doomedramen** [comment]
You have to follow the docs where it tells you to set the timezone and then restart. the reason you are getting that error is your system thinks you are in the past.

**Comment by HoudiniCerini** [comment]
I didn't see any instructions for that how the heck do I do do that I
watched all of the YouTubes and all...

**Comment by doomedramen** [comment]
The front page of this repo.Jpe230/SonicPad-Debian: Port of Debian for the SonicPad (Allwinner R818)github.comOn 4 May 2024, at 20:12, CPT.R3DB3ARD ***@***.***> wrote:﻿
I didn't see any instructions for that how the heck do I do do that I

watched all of the YouTubes and all...

**Comment by HoudiniCerini** [comment]
I got it all figured out just gotta get the adxl set up and we will be gtg
🤙🏻
