### ISSUE TITLE
A single usb port in dev/serial/

### ISSUE THREAD

**Issue by rto54** [Jpe230/SonicPad-Debian#6]
Hello,

Thanks for your work.
I managed to install the release, but in dev/serial/by-id, I only see the usb port usb-1a86_USB_Serial-if00-port0 and not the other three...

thanks

**Comment by nofuturekid** [comment]
Because if nothing is connected to the other ports there is nothing you can see, or if it is a device not exposing a serial at all.

If you want to know if the Pad has recognised your USB devices either look into 'dmesg' or 'lsusb'.

**Comment by rto54** [comment]
Ok thanks
